#!/usr/bin/env node
/**
 * Generates src/constants/version.ts with the current UNIX timestamp as the build version.
 *
 * Run: node scripts/gen-version.js
 *
 * The timestamp ensures every build gets a unique, monotonically increasing version
 * number that can't collide — no need to remember to bump semver manually.
 */
const fs = require('fs');
const path = require('path');

const timestamp = Math.floor(Date.now() / 1000);
const human = new Date(timestamp * 1000).toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

const content = [
  '// AUTO-GENERATED by scripts/gen-version.js — DO NOT EDIT BY HAND',
  `export const BUILD_VERSION = '${timestamp}';`,
  `export const BUILD_DATE = '${human}';`,
  '',
].join('\n');

const outPath = path.resolve(__dirname, '..', 'src', 'constants', 'version.ts');
fs.writeFileSync(outPath, content, 'utf-8');
console.log(`Version written: ${timestamp} (${human}) → ${outPath}`);